---
  - ansible.builtin.include_tasks: setup-rhsm.yml
    when: ansible_distribution == 'RedHat'  

  - ansible.builtin.include_tasks: setup-pkg-repositories.yml
    
  - ansible.builtin.include_tasks: setup-networking.yml

  - ansible.builtin.include_tasks: join-domain.yml
    when: join_domain.enabled | bool

  - ansible.builtin.include_tasks: setup-storage.yml

  - ansible.builtin.include_tasks: setup-hardening.yml

  - name: Ensure lingering enabled
    become: true
    ansible.builtin.command: "loginctl enable-linger ansible"

  - name: Allow the ansible user to run any commands as root
    community.general.sudoers:
      name: ansible-as-root
      state: present
      user: "{{ container.user.name }}"
      runas: root
      commands: ALL