---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: rhel9-ubi
    image: ubi9:9.4-1214
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
driver:
  name: podman
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman
provisioner:
  name: ansible
  lint: 
    name: "ansible-lint"
